version: "3.5"
services:
  node:
    # Do not set image field here, it will be set automatically by the sdk.
    build:
      context: .
      args:
        UPSTREAM_VERSION: >-
          2.1.0@sha256:28f5db3a37275edecb3b4d52f2d254832bf3346d9464a538c419575a40d8b744
    ports:
      - "3101:3101/tcp"
      - 9191:9191/tcp
      - 9191:9191/udp
      - 9192:9192/tcp
      - 9192:9192/udp
      - 9193:9193/tcp
      - 9193:9193/udp
      - 9194:9194/tcp
      - 9194:9194/udp
      - 9195:9195/tcp
      - 9195:9195/udp
      - 9196:9196/tcp
      - 9196:9196/udp
      - 9197:9197/tcp
      - 9197:9197/udp
      - 9198:9198/tcp
      - 9198:9198/udp
      - 9199:9199/tcp
      - 9199:9199/udp
    volumes:
      - "db:/app/hoprd-db"
    security_opt:
      - "seccomp:unconfined"
    environment:
      RUST_LOG: info
      HOPRD_CONFIGURATION_FILE_PATH: /app/hoprd.cfg.yaml
      HOPRD_HOST: "127.0.0.1:9191"
      HOPRD_SAFE_ADDRESS: 0x
      HOPRD_MODULE_ADDRESS: 0x
      HOPRD_HEARTBEAT_THRESHOLD: 60
      HOPRD_HEARTBEAT_INTERVAL: 20
      HOPRD_HEARTBEAT_VARIANCE: 1
      HOPRD_PASSWORD: ""
      HOPRD_PROVIDER: ""
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
  admin:
    # The actual image name  will be set automatically by the sdk.
    # This tag only serves to pull the correct image during build.
    build:
      context: ./hopr-admin
    image: >-
      europe-west3-docker.pkg.dev/hoprassociation/docker-images/hopr-admin:2.1.7
    ports:
      - "3100:4677"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
volumes:
  db: {}
