name: Build (experimental package)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and upload to IPFS
        run: |
          npm install
          npx @dappnode/dappnodesdk build \
            --provider "remote" \
            --verbose
