name: Merge
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build.yml
    with:
      version_type: pr
