name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      version_type: commit