name: Build (release package)

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
          npx @dappnode/dappnodesdk build
          npx @dappnode/dappnodesdk publish patch \
            --provider "remote" \
            --upload_to "ipfs" \
            --verbose \
            --github_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0x7305356ad936A06c4ea5DF45AD5E5C3ff9Db818E"
